---
# Labels for the repository
# Synced by .github/workflows/labels.yml
# Used by release-drafter for changelog categories

# 🚨 Breaking changes
- name: "breaking-change"
  color: "b60205"
  description: "Introduces a breaking change"

# ✨ New features
- name: "new-feature"
  color: "a2eeef"
  description: "New feature"

- name: "feature"
  color: "a2eeef"
  description: "New feature or request"

# 🐛 Bug fixes
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "bugfix"
  color: "d73a4a"
  description: "Bug fix"

- name: "fix"
  color: "d73a4a"
  description: "A fix for an issue"

# 🚀 Enhancements
- name: "enhancement"
  color: "84b6eb"
  description: "Improvement to existing functionality"

- name: "refactor"
  color: "84b6eb"
  description: "Code refactoring"

- name: "performance"
  color: "84b6eb"
  description: "Performance improvement"

# 🧰 Maintenance
- name: "maintenance"
  color: "fef2c0"
  description: "Maintenance tasks"

- name: "chore"
  color: "fef2c0"
  description: "Routine tasks and chores"

- name: "ci"
  color: "fef2c0"
  description: "CI/CD and workflow changes"

# 📚 Documentation
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "docs"
  color: "0075ca"
  description: "Documentation changes"

# ⬆️ Dependencies
- name: "dependencies"
  color: "0366d6"
  description: "Dependency updates"

# Version control (for release-drafter)
- name: "major"
  color: "b60205"
  description: "Major version bump"

- name: "minor"
  color: "fbca04"
  description: "Minor version bump"

# Skip changelog
- name: "skip-changelog"
  color: "ededed"
  description: "Skip this PR in the changelog"

# Issue-specific labels
- name: "question"
  color: "d876e3"
  description: "Further information is requested"

- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"
