# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import bravia_control_pb2 as bravia__control__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        " but the generated code in bravia_control_pb2_grpc.py depends on"
        f" grpcio>={GRPC_GENERATED_VERSION}."
        f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ControlDeviceServiceStub:
    """Service definition"""

    def __init__(self, channel):
        """
        Constructor.

        Args:
            channel: A grpc.Channel.

        """
        self.ConfirmSignin = channel.unary_unary(
            "/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/ConfirmSignin",
            request_serializer=bravia__control__pb2.ConfirmSigninRequest.SerializeToString,
            response_deserializer=bravia__control__pb2.ConfirmSigninResponse.FromString,
            _registered_method=True,
        )
        self.ConfirmKeys = channel.unary_unary(
            "/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/ConfirmKeys",
            request_serializer=bravia__control__pb2.ConfirmKeysRequest.SerializeToString,
            response_deserializer=bravia__control__pb2.ConfirmKeysResponse.FromString,
            _registered_method=True,
        )
        self.GetSessionRandom = channel.unary_unary(
            "/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/GetSessionRandom",
            request_serializer=bravia__control__pb2.GetSessionRandomRequest.SerializeToString,
            response_deserializer=bravia__control__pb2.GetSessionRandomResponse.FromString,
            _registered_method=True,
        )
        self.GetStatesWithAuth = channel.unary_unary(
            "/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/GetStatesWithAuth",
            request_serializer=bravia__control__pb2.GetStatesWithAuthRequest.SerializeToString,
            response_deserializer=bravia__control__pb2.GetStatesWithAuthResponse.FromString,
            _registered_method=True,
        )
        self.StartNotifyStates = channel.unary_stream(
            "/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/StartNotifyStates",
            request_serializer=bravia__control__pb2.StartNotifyStatesRequest.SerializeToString,
            response_deserializer=bravia__control__pb2.StartNotifyStatesResponse.FromString,
            _registered_method=True,
        )
        self.ExecCommandWithAuth = channel.unary_unary(
            "/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/ExecCommandWithAuth",
            request_serializer=bravia__control__pb2.ExecCommandWithAuthRequest.SerializeToString,
            response_deserializer=bravia__control__pb2.ExecCommandWithAuthResponse.FromString,
            _registered_method=True,
        )


class ControlDeviceServiceServicer:
    """Service definition"""

    def ConfirmSignin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ConfirmKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSessionRandom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStatesWithAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StartNotifyStates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExecCommandWithAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ControlDeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ConfirmSignin": grpc.unary_unary_rpc_method_handler(
            servicer.ConfirmSignin,
            request_deserializer=bravia__control__pb2.ConfirmSigninRequest.FromString,
            response_serializer=bravia__control__pb2.ConfirmSigninResponse.SerializeToString,
        ),
        "ConfirmKeys": grpc.unary_unary_rpc_method_handler(
            servicer.ConfirmKeys,
            request_deserializer=bravia__control__pb2.ConfirmKeysRequest.FromString,
            response_serializer=bravia__control__pb2.ConfirmKeysResponse.SerializeToString,
        ),
        "GetSessionRandom": grpc.unary_unary_rpc_method_handler(
            servicer.GetSessionRandom,
            request_deserializer=bravia__control__pb2.GetSessionRandomRequest.FromString,
            response_serializer=bravia__control__pb2.GetSessionRandomResponse.SerializeToString,
        ),
        "GetStatesWithAuth": grpc.unary_unary_rpc_method_handler(
            servicer.GetStatesWithAuth,
            request_deserializer=bravia__control__pb2.GetStatesWithAuthRequest.FromString,
            response_serializer=bravia__control__pb2.GetStatesWithAuthResponse.SerializeToString,
        ),
        "StartNotifyStates": grpc.unary_stream_rpc_method_handler(
            servicer.StartNotifyStates,
            request_deserializer=bravia__control__pb2.StartNotifyStatesRequest.FromString,
            response_serializer=bravia__control__pb2.StartNotifyStatesResponse.SerializeToString,
        ),
        "ExecCommandWithAuth": grpc.unary_unary_rpc_method_handler(
            servicer.ExecCommandWithAuth,
            request_deserializer=bravia__control__pb2.ExecCommandWithAuthRequest.FromString,
            response_serializer=bravia__control__pb2.ExecCommandWithAuthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ControlDeviceService:
    """Service definition"""

    @staticmethod
    def ConfirmSignin(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/ConfirmSignin",
            bravia__control__pb2.ConfirmSigninRequest.SerializeToString,
            bravia__control__pb2.ConfirmSigninResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ConfirmKeys(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/ConfirmKeys",
            bravia__control__pb2.ConfirmKeysRequest.SerializeToString,
            bravia__control__pb2.ConfirmKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSessionRandom(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/GetSessionRandom",
            bravia__control__pb2.GetSessionRandomRequest.SerializeToString,
            bravia__control__pb2.GetSessionRandomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStatesWithAuth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/GetStatesWithAuth",
            bravia__control__pb2.GetStatesWithAuthRequest.SerializeToString,
            bravia__control__pb2.GetStatesWithAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StartNotifyStates(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/StartNotifyStates",
            bravia__control__pb2.StartNotifyStatesRequest.SerializeToString,
            bravia__control__pb2.StartNotifyStatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExecCommandWithAuth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/ExecCommandWithAuth",
            bravia__control__pb2.ExecCommandWithAuthRequest.SerializeToString,
            bravia__control__pb2.ExecCommandWithAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
