---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type"
        required: false
        type: choice
        default: "stable"
        options:
          - stable
          - beta
          - alpha
          - rc

jobs:
  update_release_draft:
    name: ✏️ Draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🚀 Run Release Drafter (stable)
        if: github.event_name != 'workflow_dispatch' || inputs.release_type == 'stable'
        uses: release-drafter/release-drafter@v6.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚀 Run Release Drafter (pre-release)
        if: github.event_name == 'workflow_dispatch' && inputs.release_type != 'stable'
        uses: release-drafter/release-drafter@v6.4.0
        with:
          prerelease: true
          prerelease-identifier: ${{ inputs.release_type }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
